# Generated by Django 5.0.6 on 2024-07-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fotoPerfil',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
